### ISSUE TITLE
no work international in english but it is already implemented the files

### ISSUE THREAD

**Issue by RomanFama592** [midudev/esland-web#121]
![image](https://github.com/midudev/esland-web/assets/107817690/79887569-f130-4456-830a-1531179b9867)

**Comment by eliasdanielr** [comment]
The page is only available in Spanish (es) and Catalan (ca).

**Comment by juanjosenavarro13** [comment]
![image](https://github.com/midudev/esland-web/assets/44004611/0b3090ef-7c4d-4765-a3b3-25c22bac23e0)
https://esland-web.vercel.app/en/vote

**Comment by RomanFama592** [comment]
> ![image](https://private-user-images.githubusercontent.com/44004611/302644553-0b3090ef-7c4d-4765-a3b3-25c22bac23e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjg1ODMsIm5iZiI6MTcwNzIyODI4MywicGF0aCI6Ii80NDAwNDYxMS8zMDI2NDQ1NTMtMGIzMDkwZWYtN2M0ZC00NzY1LWEzYjMtMjVjMjJiYWMyM2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDE0MDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjYjVjOGZkNTMwODQ3Y2IxZjQ3N2JjZGVlYTU4MTM2ODZlNmFhZjViMDc3MTczZmFlNGViMTAzOTg0NTI5MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dbXz1D-H1G_HjeilEQpG4YioLluJz6bPr1Uh2uaQh6M) https://esland-web.vercel.app/en/vote

Genius, idol. The "archive" part of the translation is incomplete, it appears in Spanish. But good start
