### ISSUE TITLE
Problemas con el MobileMenu

### ISSUE THREAD

**Issue by ghost** [midudev/esland-web#51]
Por alguna razón, la carga de JavaScript en la página no se está realizando correctamente, al menos eso es lo que creo que está sucediendo.

Pueden observar este ejemplo, donde el MobileMenu funciona perfectamente. Sin embargo, al cambiar de página y activar las WebTransitions, el menú deja de funcionar por alguna razón. Solo recupera su funcionalidad cuando se realiza una recarga completa de la página.

Esto me ha sucedido en paginas personales como mi portafolio, y solo pude solucionarlo agragando el MobileMenu con algun framework como react

Adjunto evidencia de lo que sucede

https://github.com/midudev/esland-web/assets/105263575/c6b897f7-d8a6-4d48-8fa4-2b662da06230

**Comment by PedroReyes** [comment]
Hola,

He creado esta pull request para solventarlo [aquí](https://github.com/midudev/esland-web/pull/54)

Un saludo,
Pedro Reyes.
