### ISSUE TITLE
Problemas para la visualización de /archivo

### ISSUE THREAD

**Issue by ossavemu** [midudev/esland-web#53]
![image](https://github.com/midudev/esland-web/assets/90299049/99816b50-0ce2-4de3-bd4a-af62f21e8966)

Esta parte está dando mucho lag y no se ve bien en mi pc, tanto que se traba al intentar de capturar video.

**Comment by iamabhijeet2003** [comment]
Está solucionado ya. Ahora se ve bien.

**Comment by manujoz** [comment]
@midudev please this issue seems solved 😉
